[package]
name = "fellows"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-files = "0.6.2"
actix-web = { version = "4.4.0", features = ["openssl"] }
badge-maker = "0.3.1"
cached = "0.46.0"
clap = { version = "4.4.7", features = ["derive"] }
env_logger = "0.10.1"
fancy-regex = "0.11.0"
html-escape = "0.2.13"
log = "0.4.20"
openssl = { version = "0.10", features = ["v110"] }
parity-scale-codec = { version = "3.6.5", features = ["derive"] }
reqwest = "0.11.22"
sailfish = "0.8.3"
scale-info = "2.10.0"
serde = "1.0.192"
serde_json = "1.0.108"
sp-core = { version = "25.0.0", default-features = false, features = ["std"] }
subxt = "0.32.1"
tokio = "1.34.0"
