version: "3"
services:
  fellowship:
    container_name: fellowship
    image: ghcr.io/ggwpez/swc:master
    ports:
      - "443:8080"
    command: >
      sh -c "git config --global --add safe.directory '*' && 
      subweight-web --root /repos/ --repos substrate polkadot cumulus chain --endpoint '0.0.0.0' --cert /certs/cert.pem --key /certs/key.pem"
    volumes:
      - /home/vados/certs:/certs:ro
      - /home/vados/repos:/repos
    healthcheck:
      test: ["CMD", "curl", "-f", "0.0.0.0:8080"]
      interval: 60s
      timeout: 10s
      retries: 10

  watchtower:
    image: containrrr/watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    # Check every ten minutes
    command: --interval 600 compliance
